// Error handling
// try {} catch (...) {} // catches any error
// try {} catch (const std::exception& e) {}